# Generate the named-entity table from the WHATWG named character reference list.
# Run automatically by "make build"; emitted to build/entities.awk:
#
#   awk -f scripts/gen-entities.awk scripts/entities.json > build/entities.awk
#
# Each emitted record is "name;:codepoint[,codepoint...]" and records are packed
# into space-separated chunks small enough for every target awk to hold as a
# string literal (mawk caps literals around 8-16 KB; we stay well under). The
# generated init_entity_data() rebuilds the blob at run time; load_entities() in
# inlines.awk splits it and decodes the codepoints with character_from_codepoint.
BEGIN {
    chunk_limit = 1900
    chunk = ""
    print "# Generated by \"make build\" via scripts/gen-entities.awk from scripts/entities.json."
    print "# Do not edit by hand."
    print "function init_entity_data() {"
    print "    ENTITY_DATA = \"\""
}

# Only the semicolon-terminated entities are valid CommonMark references.
/^  "&[^"]*;":/ {
    name = $0
    sub(/^  "&/, "", name)
    sub(/;":.*/, "", name)

    cps = $0
    sub(/.*"codepoints": \[/, "", cps)
    sub(/\].*/, "", cps)
    gsub(/ /, "", cps)

    record = name ";:" cps " "
    if (length(chunk) + length(record) > chunk_limit) {
        emit_chunk(chunk)
        chunk = ""
    }
    chunk = chunk record
}

END {
    if (chunk != "") {
        emit_chunk(chunk)
    }
    print "}"
}

function emit_chunk(text) {
    print "    ENTITY_DATA = ENTITY_DATA \"" text "\""
}
